name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install NPM dependencies
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Build parcel
      run: parcel build index.html --out-dir dist

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'dist/'
        dest: 'root@isah.andros.dev:/root/isah.andros.dev'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
